package mybiz.inventory.model;

// Generated 2015-2-14 12:51:33 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ItemIn generated by hbm2java
 */
public class ItemIn implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long itemInId;
	private String code;
	private String name;
	private BigDecimal purcahasPrice;
	private Date purchaseDatetime;
	private Integer purchaseSize;
	private String address;
	private BigDecimal telephone;
	private String isTrans;

	public ItemIn() {
	}

	public ItemIn(int itemInId) {
		this.itemInId = itemInId;
	}

	public ItemIn(int itemInId, String code, String name,
			BigDecimal purcahasPrice, Date purchaseDatetime,
			Integer purchaseSize, String address, BigDecimal telephone,
			String isTrans) {
		this.itemInId = itemInId;
		this.code = code;
		this.name = name;
		this.purcahasPrice = purcahasPrice;
		this.purchaseDatetime = purchaseDatetime;
		this.purchaseSize = purchaseSize;
		this.address = address;
		this.telephone = telephone;
		this.isTrans = isTrans;
	}

	public long getItemInId() {
		return this.itemInId;
	}

	public void setItemInId(long itemInId) {
		this.itemInId = itemInId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPurcahasPrice() {
		return this.purcahasPrice;
	}

	public void setPurcahasPrice(BigDecimal purcahasPrice) {
		this.purcahasPrice = purcahasPrice;
	}

	public Date getPurchaseDatetime() {
		return this.purchaseDatetime;
	}

	public void setPurchaseDatetime(Date purchaseDatetime) {
		this.purchaseDatetime = purchaseDatetime;
	}

	public Integer getPurchaseSize() {
		return this.purchaseSize;
	}

	public void setPurchaseSize(Integer purchaseSize) {
		this.purchaseSize = purchaseSize;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public BigDecimal getTelephone() {
		return this.telephone;
	}

	public void setTelephone(BigDecimal telephone) {
		this.telephone = telephone;
	}

	public String getIsTrans() {
		return this.isTrans;
	}

	public void setIsTrans(String isTrans) {
		this.isTrans = isTrans;
	}

}
