
DROP TABLE ITEM_SELL if not exists;
DROP TABLE ITEM_IN if not exists;

CREATE TABLE ITEM_IN
(
ITEM_IN_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
CONSTRAINT ITEM_IN_PK PRIMARY KEY, 
CODE VARCHAR(20),
NAME VARCHAR(200),
PURCAHAS_PRICE DECIMAL(20,2),
PURCHASE_DATETIME DATE,
PURCHASE_SIZE NUMERIC(8,0),
ADDRESS LONG VARCHAR,
TELEPHONE NUMERIC(25,0),
IS_TRANS VARCHAR(5)
);

CREATE TABLE ITEM_SELL
(
ITEM_SELL_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
CONSTRAINT ITEM_SELL_PK PRIMARY KEY,
ITEM_SELL_ITEM_IN_ID INT,
SELL_SIEZ NUMERIC(8,0),
SELL_PRICE DECIMAL(20,2),
SELL_DATETIME TIMESTAMP,
SELL_ADDRESS LONG VARCHAR,
SELL_TELPHONE NUMERIC(25,0)
);

ALTER TABLE ITEM_SELL ADD CONSTRAINT FOREIGNKEY_ITEM_IN_ID_FK
Foreign Key (ITEM_SELL_ITEM_IN_ID) REFERENCES ITEM_IN (ITEM_IN_ID);

--ALTER TABLE ITEM_STOCK_EVENT DROP CONSTRAINT ITEM_FK;