var accessoryList = [
	{
		display:'配件-水管-2分PE-',
		ptype:'配件',
		brand:'水管',
		pname:'2分PE',
		standard:''
	},
	{
		display:'配件-水管-3分PE-',
		ptype:'配件',
		brand:'水管',
		pname:'3分PE',
		standard:''
	},
	{
		display:'配件-水管-2分CCK-',
		ptype:'配件',
		brand:'水管',
		pname:'2分CCK',
		standard:''
	},
	{
		display:'配件-水管-3分CCK-',
		ptype:'配件',
		brand:'水管',
		pname:'3分CCK',
		standard:''
	},
	{
		display:'配件-变压器-1.2A-',
		ptype:'配件',
		brand:'变压器',
		pname:'1.2A',
		standard:''
	},
	{
		display:'配件-变压器-1.5A-',
		ptype:'配件',
		brand:'变压器',
		pname:'1.5A',
		standard:''
	},
	{
		display:'配件-变压器-1.5A（外置）-',
		ptype:'配件',
		brand:'变压器',
		pname:'1.5A（外置）',
		standard:''
	},
	{
		display:'配件-变压器-2.0A-',
		ptype:'配件',
		brand:'变压器',
		pname:'2.0A',
		standard:''
	},
	{
		display:'配件-变压器-3.0A-',
		ptype:'配件',
		brand:'变压器',
		pname:'3.0A',
		standard:''
	},
	{
		display:'配件-变压器-5A-',
		ptype:'配件',
		brand:'变压器',
		pname:'5A',
		standard:''
	},
	{
		display:'配件-冠宇达-2A外置-',
		ptype:'配件',
		brand:'冠宇达',
		pname:'2A外置',
		standard:''
	},
	{
		display:'配件-铁板-一级板-',
		ptype:'配件',
		brand:'铁板',
		pname:'一级板',
		standard:''
	},
	{
		display:'配件-铁板-二级板-',
		ptype:'配件',
		brand:'铁板',
		pname:'二级板',
		standard:''
	},
	{
		display:'配件-铁板-三级板-',
		ptype:'配件',
		brand:'铁板',
		pname:'三级板',
		standard:''
	},
	{
		display:'配件-铁板-纯水机板-',
		ptype:'配件',
		brand:'铁板',
		pname:'纯水机板',
		standard:''
	},
	{
		display:'配件-豪华鹅颈-三叉龙头-',
		ptype:'配件',
		brand:'豪华鹅颈',
		pname:'三叉龙头',
		standard:''
	},
	{
		display:'配件-勾型鹅颈-平压式龙头-',
		ptype:'配件',
		brand:'勾型鹅颈',
		pname:'平压式龙头',
		standard:''
	},
	{
		display:'配件-豪华鹅颈-三叉龙头（快接式）-',
		ptype:'配件',
		brand:'豪华鹅颈',
		pname:'三叉龙头（快接式）',
		standard:''
	},
	{
		display:'配件-豪华鹅颈-三叉双龙头(单柄的）-',
		ptype:'配件',
		brand:'豪华鹅颈',
		pname:'三叉双龙头(单柄的）',
		standard:''
	},
	{
		display:'配件-豪华鹅颈-龙头工具（塑料）-',
		ptype:'配件',
		brand:'豪华鹅颈',
		pname:'龙头工具（塑料）',
		standard:''
	},
	{
		display:'配件-豪华鹅颈-安吉尔豪华单龙头-',
		ptype:'配件',
		brand:'豪华鹅颈',
		pname:'安吉尔豪华单龙头',
		standard:''
	},
	{
		display:'配件-TDS-测水笔（国产）三健-',
		ptype:'配件',
		brand:'TDS',
		pname:'测水笔（国产）三健',
		standard:''
	},
	{
		display:'配件-TDS-测水笔（进口）两键-',
		ptype:'配件',
		brand:'TDS',
		pname:'测水笔（进口）两键',
		standard:''
	},
	{
		display:'配件-TDS-电解器-',
		ptype:'配件',
		brand:'TDS',
		pname:'电解器',
		standard:''
	},
	{
		display:'配件-电脑控制盒-炫彩电脑盒-',
		ptype:'配件',
		brand:'电脑控制盒',
		pname:'炫彩电脑盒',
		standard:''
	},
	{
		display:'配件-电脑控制盒-外置五灯电脑盒-',
		ptype:'配件',
		brand:'电脑控制盒',
		pname:'外置五灯电脑盒',
		standard:''
	},
	{
		display:'配件-电脑控制盒-电脑盒400g-',
		ptype:'配件',
		brand:'电脑控制盒',
		pname:'电脑盒400g',
		standard:''
	},
	{
		display:'配件-电脑控制盒-内置八字电脑盒-',
		ptype:'配件',
		brand:'电脑控制盒',
		pname:'内置八字电脑盒',
		standard:''
	},
	{
		display:'配件-电脑控制盒-内置五灯电脑盒-',
		ptype:'配件',
		brand:'电脑控制盒',
		pname:'内置五灯电脑盒',
		standard:''
	},
	{
		display:'配件-电脑控制盒-进水盖（聪明盖）-',
		ptype:'配件',
		brand:'电脑控制盒',
		pname:'进水盖（聪明盖）',
		standard:''
	},
	{
		display:'配件-电脑控制盒-小连通-',
		ptype:'配件',
		brand:'电脑控制盒',
		pname:'小连通',
		standard:''
	},
	{
		display:'配件-电磁阀-进水电磁阀-',
		ptype:'配件',
		brand:'电磁阀',
		pname:'进水电磁阀',
		standard:''
	},
	{
		display:'配件-电磁阀-DCC减压阀-',
		ptype:'配件',
		brand:'电磁阀',
		pname:'DCC减压阀',
		standard:''
	},
	{
		display:'配件-电磁阀-2分减压阀-',
		ptype:'配件',
		brand:'电磁阀',
		pname:'2分减压阀',
		standard:''
	},
	{
		display:'配件-电磁阀-直减压阀-',
		ptype:'配件',
		brand:'电磁阀',
		pname:'直减压阀',
		standard:''
	},
	{
		display:'配件-电磁阀-组合电池阀-',
		ptype:'配件',
		brand:'电磁阀',
		pname:'组合电池阀',
		standard:''
	},
	{
		display:'配件-电磁阀-自动冲洗阀（18秒）-',
		ptype:'配件',
		brand:'电磁阀',
		pname:'自动冲洗阀（18秒）',
		standard:''
	},
	{
		display:'配件-电磁阀-制冷片-',
		ptype:'配件',
		brand:'电磁阀',
		pname:'制冷片',
		standard:''
	},
	{
		display:'配件-电磁阀-风扇-',
		ptype:'配件',
		brand:'电磁阀',
		pname:'风扇',
		standard:''
	},
	{
		display:'配件-开关-白色低压开关快接-',
		ptype:'配件',
		brand:'开关',
		pname:'白色低压开关快接',
		standard:''
	},
	{
		display:'配件-开关-白色高压开关快接-',
		ptype:'配件',
		brand:'开关',
		pname:'白色高压开关快接',
		standard:''
	},
	{
		display:'配件-开关-黑色低压开关-',
		ptype:'配件',
		brand:'开关',
		pname:'黑色低压开关',
		standard:''
	},
	{
		display:'配件-开关-黑色高压开关-',
		ptype:'配件',
		brand:'开关',
		pname:'黑色高压开关',
		standard:''
	},
	{
		display:'配件-开关-压力桶球阀慢接式-',
		ptype:'配件',
		brand:'开关',
		pname:'压力桶球阀慢接式',
		standard:''
	},
	{
		display:'配件-开关-压力桶球阀快接式-',
		ptype:'配件',
		brand:'开关',
		pname:'压力桶球阀快接式',
		standard:''
	},
	{
		display:'配件-快捷废水比-废水比300cc-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'废水比300cc',
		standard:''
	},
	{
		display:'配件-快捷废水比-废水比450cc-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'废水比450cc',
		standard:''
	},
	{
		display:'配件-快捷废水比-废水比1500cc-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'废水比1500cc',
		standard:''
	},
	{
		display:'配件-快捷废水比-四面阀-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'四面阀',
		standard:''
	},
	{
		display:'配件-快捷废水比-压力开关（安吉尔的）-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'压力开关（安吉尔的）',
		standard:''
	},
	{
		display:'配件-快捷废水比-逆止阀弯-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'逆止阀弯',
		standard:''
	},
	{
		display:'配件-快捷废水比-逆止阀直-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'逆止阀直',
		standard:''
	},
	{
		display:'配件-快捷废水比-余氯测试剂-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'余氯测试剂',
		standard:''
	},
	{
		display:'配件-快捷废水比-钙镁测试剂-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'钙镁测试剂',
		standard:''
	},
	{
		display:'配件-快捷废水比-PH测试剂-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'PH测试剂',
		standard:''
	},
	{
		display:'配件-快捷废水比-管剪-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'管剪',
		standard:''
	},
	{
		display:'配件-快捷废水比-生料带-',
		ptype:'配件',
		brand:'快捷废水比',
		pname:'生料带',
		standard:''
	},
	{
		display:'配件-压力桶-压力桶3.2G（铁）-',
		ptype:'配件',
		brand:'压力桶',
		pname:'压力桶3.2G（铁）',
		standard:''
	},
	{
		display:'配件-压力桶-压力桶6G(铁）-',
		ptype:'配件',
		brand:'压力桶',
		pname:'压力桶6G(铁）',
		standard:''
	},
	{
		display:'配件-压力桶-压力桶3.2G（塑料）-',
		ptype:'配件',
		brand:'压力桶',
		pname:'压力桶3.2G（塑料）',
		standard:''
	},
	{
		display:'配件-压力桶-手提桶（塑料）-',
		ptype:'配件',
		brand:'压力桶',
		pname:'手提桶（塑料）',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-膜壳75g-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'膜壳75g',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-RO膜壳75g直-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'RO膜壳75g直',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-RO膜壳75g快接-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'RO膜壳75g快接',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-RO膜壳300g-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'RO膜壳300g',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-RO膜壳400g-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'RO膜壳400g',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-10寸滤瓶扳手白色-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'10寸滤瓶扳手白色',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-意式瓶2分口-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'意式瓶2分口',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-透明意式瓶4分口-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'透明意式瓶4分口',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-平夹-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'平夹',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-平夹300g-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'平夹300g',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-大双夹-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'大双夹',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-大小夹-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'大小夹',
		standard:''
	},
	{
		display:'配件-膜壳/扳手-子母夹-',
		ptype:'配件',
		brand:'膜壳/扳手',
		pname:'子母夹',
		standard:''
	},
];
