var filterCartridgeList = [
	{
		display:'滤芯-安吉尔-后置活性炭小T-',
		ptype:'滤芯',
		brand:'安吉尔',
		pname:'后置活性炭小T',
		standard:''
	},
	{
		display:'滤芯-安吉尔-压缩活性炭-',
		ptype:'滤芯',
		brand:'安吉尔',
		pname:'压缩活性炭',
		standard:''
	},
	{
		display:'滤芯-安吉尔-一体PP棉-',
		ptype:'滤芯',
		brand:'安吉尔',
		pname:'一体PP棉',
		standard:''
	},
	{
		display:'滤芯-安吉尔-一体前置活性炭-',
		ptype:'滤芯',
		brand:'安吉尔',
		pname:'一体前置活性炭',
		standard:''
	},
	{
		display:'滤芯-安吉尔-一体后置活性炭-',
		ptype:'滤芯',
		brand:'安吉尔',
		pname:'一体后置活性炭',
		standard:''
	},
	{
		display:'滤芯-安吉尔-10寸PP棉-',
		ptype:'滤芯',
		brand:'安吉尔',
		pname:'10寸PP棉',
		standard:''
	},
	{
		display:'滤芯-安吉尔-10寸120J超滤膜-',
		ptype:'滤芯',
		brand:'安吉尔',
		pname:'10寸120J超滤膜',
		standard:''
	},
	{
		display:'滤芯-泉来-饮水宝宝-',
		ptype:'滤芯',
		brand:'泉来',
		pname:'饮水宝宝',
		standard:''
	},
	{
		display:'滤芯-汇通RO膜-50G-',
		ptype:'滤芯',
		brand:'汇通RO膜',
		pname:'50G',
		standard:''
	},
	{
		display:'滤芯-汇通RO膜-75G-',
		ptype:'滤芯',
		brand:'汇通RO膜',
		pname:'75G',
		standard:''
	},
	{
		display:'滤芯-汇通RO膜-100G-',
		ptype:'滤芯',
		brand:'汇通RO膜',
		pname:'100G',
		standard:''
	},
	{
		display:'滤芯-汇通RO膜-200G-',
		ptype:'滤芯',
		brand:'汇通RO膜',
		pname:'200G',
		standard:''
	},
	{
		display:'滤芯-汇通RO膜-300G-',
		ptype:'滤芯',
		brand:'汇通RO膜',
		pname:'300G',
		standard:''
	},
	{
		display:'滤芯-汇通RO膜-800G（4021/4031）-',
		ptype:'滤芯',
		brand:'汇通RO膜',
		pname:'800G（4021/4031）',
		standard:''
	},
	{
		display:'滤芯-流体RO膜-125G-',
		ptype:'滤芯',
		brand:'流体RO膜',
		pname:'125G',
		standard:''
	},
	{
		display:'滤芯-美的-PP棉（绿色标签）-10寸',
		ptype:'滤芯',
		brand:'美的',
		pname:'PP棉（绿色标签）',
		standard:'10寸'
	},
	{
		display:'滤芯-美的-颗粒活性炭-10寸',
		ptype:'滤芯',
		brand:'美的',
		pname:'颗粒活性炭',
		standard:'10寸'
	},
	{
		display:'滤芯-美的-F1PP棉-',
		ptype:'滤芯',
		brand:'美的',
		pname:'F1PP棉',
		standard:''
	},
	{
		display:'滤芯-美的-F1前置活性炭-',
		ptype:'滤芯',
		brand:'美的',
		pname:'F1前置活性炭',
		standard:''
	},
	{
		display:'滤芯-美的-F1后置活性炭-',
		ptype:'滤芯',
		brand:'美的',
		pname:'F1后置活性炭',
		standard:''
	},
	{
		display:'滤芯-美的-F150gRO反渗透膜-',
		ptype:'滤芯',
		brand:'美的',
		pname:'F150gRO反渗透膜',
		standard:''
	},
	{
		display:'滤芯-美的-M6PP棉-',
		ptype:'滤芯',
		brand:'美的',
		pname:'M6PP棉',
		standard:''
	},
	{
		display:'滤芯-美的-M6前置活性炭-',
		ptype:'滤芯',
		brand:'美的',
		pname:'M6前置活性炭',
		standard:''
	},
	{
		display:'滤芯-美的-M6后置活性炭-',
		ptype:'滤芯',
		brand:'美的',
		pname:'M6后置活性炭',
		standard:''
	},
	{
		display:'滤芯-美的-M6超滤膜-',
		ptype:'滤芯',
		brand:'美的',
		pname:'M6超滤膜',
		standard:''
	},
	{
		display:'滤芯-美的-M6RO膜-',
		ptype:'滤芯',
		brand:'美的',
		pname:'M6RO膜',
		standard:''
	},
	{
		display:'滤芯-美的-M8PP棉-',
		ptype:'滤芯',
		brand:'美的',
		pname:'M8PP棉',
		standard:''
	},
	{
		display:'滤芯-美的-M8前置活性炭-',
		ptype:'滤芯',
		brand:'美的',
		pname:'M8前置活性炭',
		standard:''
	},
	{
		display:'滤芯-美的-M8后置活性炭-',
		ptype:'滤芯',
		brand:'美的',
		pname:'M8后置活性炭',
		standard:''
	},
	{
		display:'滤芯-美的-M8超滤膜-',
		ptype:'滤芯',
		brand:'美的',
		pname:'M8超滤膜',
		standard:''
	},
	{
		display:'滤芯-美的-超滤膜12寸-12寸',
		ptype:'滤芯',
		brand:'美的',
		pname:'超滤膜12寸',
		standard:'12寸'
	},
	{
		display:'滤芯-爱惠普-PP棉-10寸',
		ptype:'滤芯',
		brand:'爱惠普',
		pname:'PP棉',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-颗粒树脂滤芯（平压式）-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'颗粒树脂滤芯（平压式）',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-PP棉（1微米）-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'PP棉（1微米）',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-颗粒活性炭-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'颗粒活性炭',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-树脂大T-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'树脂大T',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-一体PP棉-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'一体PP棉',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-PP棉（1微米）-11寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'PP棉（1微米）',
		standard:'11寸'
	},
	{
		display:'滤芯-普通-颗粒活性炭-11寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'颗粒活性炭',
		standard:'11寸'
	},
	{
		display:'滤芯-普通-压缩活性炭-11寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'压缩活性炭',
		standard:'11寸'
	},
	{
		display:'滤芯-普通-PP棉（1微米）-20寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'PP棉（1微米）',
		standard:'20寸'
	},
	{
		display:'滤芯-普通-颗粒活性炭-20寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'颗粒活性炭',
		standard:'20寸'
	},
	{
		display:'滤芯-普通-压缩活性炭-20寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'压缩活性炭',
		standard:'20寸'
	},
	{
		display:'滤芯-普通-一体麦饭石-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'一体麦饭石',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-一体超滤膜-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'一体超滤膜',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-一体后置活性炭大T33-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'一体后置活性炭大T33',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-插入式超滤膜（有壳）-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'插入式超滤膜（有壳）',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-平压式超滤膜-',
		ptype:'滤芯',
		brand:'普通',
		pname:'平压式超滤膜',
		standard:''
	},
	{
		display:'滤芯-普通-弱碱性滤芯-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'弱碱性滤芯',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-插入式超滤膜-9寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'插入式超滤膜',
		standard:'9寸'
	},
	{
		display:'滤芯-普通-锁牙式陶瓷滤芯-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'锁牙式陶瓷滤芯',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-平压式陶瓷滤芯-10寸',
		ptype:'滤芯',
		brand:'普通',
		pname:'平压式陶瓷滤芯',
		standard:'10寸'
	},
	{
		display:'滤芯-普通-锁牙超滤膜-',
		ptype:'滤芯',
		brand:'普通',
		pname:'锁牙超滤膜',
		standard:''
	},
	{
		display:'滤芯-上海-后置活性炭小T-10寸',
		ptype:'滤芯',
		brand:'上海',
		pname:'后置活性炭小T',
		standard:'10寸'
	},
	{
		display:'滤芯-上海-PP棉（1微米）-10寸',
		ptype:'滤芯',
		brand:'上海',
		pname:'PP棉（1微米）',
		standard:'10寸'
	},
	{
		display:'滤芯-上海-颗粒活性炭-10寸',
		ptype:'滤芯',
		brand:'上海',
		pname:'颗粒活性炭',
		standard:'10寸'
	},
	{
		display:'滤芯-上海-PP棉（1微米）-11寸',
		ptype:'滤芯',
		brand:'上海',
		pname:'PP棉（1微米）',
		standard:'11寸'
	},
	{
		display:'滤芯-沁园-沁园水艺膜50g-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'沁园水艺膜50g',
		standard:''
	},
	{
		display:'滤芯-沁园-沁园RO膜-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'沁园RO膜',
		standard:''
	},
	{
		display:'滤芯-沁园-后置小T-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'后置小T',
		standard:''
	},
	{
		display:'滤芯-沁园-明杆后置小T-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'明杆后置小T',
		standard:''
	},
	{
		display:'滤芯-沁园-平压式压缩碳-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'平压式压缩碳',
		standard:''
	},
	{
		display:'滤芯-沁园-平压式PP棉-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'平压式PP棉',
		standard:''
	},
	{
		display:'滤芯-沁园-插入式9寸PP-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'插入式9寸PP',
		standard:''
	},
	{
		display:'滤芯-沁园-插入式颗粒碳-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'插入式颗粒碳',
		standard:''
	},
	{
		display:'滤芯-沁园-明杆颗粒碳-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'明杆颗粒碳',
		standard:''
	},
	{
		display:'滤芯-沁园-明杆式压缩碳-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'明杆式压缩碳',
		standard:''
	},
	{
		display:'滤芯-沁园-明杆式超滤膜-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'明杆式超滤膜',
		standard:''
	},
	{
		display:'滤芯-沁园-插入式超滤膜-10寸',
		ptype:'滤芯',
		brand:'沁园',
		pname:'插入式超滤膜',
		standard:'10寸'
	},
	{
		display:'滤芯-沁园-锁牙9寸PP棉-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'锁牙9寸PP棉',
		standard:''
	},
	{
		display:'滤芯-沁园-普通龙头陶瓷滤芯-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'普通龙头陶瓷滤芯',
		standard:''
	},
	{
		display:'滤芯-沁园-明杆PP-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'明杆PP',
		standard:''
	},
	{
		display:'滤芯-沁园-沁园自制超滤膜-',
		ptype:'滤芯',
		brand:'沁园',
		pname:'沁园自制超滤膜',
		standard:''
	},
];
