var jointList = [
	{
		display:'接头--1分转2分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'1分转2分弯头快接',
		standard:''
	},
	{
		display:'接头--2分内牙转2分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'2分内牙转2分弯头快接',
		standard:''
	},
	{
		display:'接头--2分进水三通（三通球阀）(铁)-',
		ptype:'接头',
		brand:'',
		pname:'2分进水三通（三通球阀）(铁)',
		standard:''
	},
	{
		display:'接头--2分开关球阀塑料-',
		ptype:'接头',
		brand:'',
		pname:'2分开关球阀塑料',
		standard:''
	},
	{
		display:'接头--2分T型三通快接-',
		ptype:'接头',
		brand:'',
		pname:'2分T型三通快接',
		standard:''
	},
	{
		display:'接头--2分Y型三通-',
		ptype:'接头',
		brand:'',
		pname:'2分Y型三通',
		standard:''
	},
	{
		display:'接头--2分侧三通-',
		ptype:'接头',
		brand:'',
		pname:'2分侧三通',
		standard:''
	},
	{
		display:'接头--2分内丝牙转2分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'2分内丝牙转2分直通快接',
		standard:''
	},
	{
		display:'接头--2分外对丝-',
		ptype:'接头',
		brand:'',
		pname:'2分外对丝',
		standard:''
	},
	{
		display:'接头--2分外丝牙转2分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'2分外丝牙转2分弯头快接',
		standard:''
	},
	{
		display:'接头--2分外丝转2分直通-',
		ptype:'接头',
		brand:'',
		pname:'2分外丝转2分直通',
		standard:''
	},
	{
		display:'接头--2分外丝转3分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'2分外丝转3分弯头快接',
		standard:''
	},
	{
		display:'接头--2分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'2分弯头快接',
		standard:''
	},
	{
		display:'接头--2分正三通-',
		ptype:'接头',
		brand:'',
		pname:'2分正三通',
		standard:''
	},
	{
		display:'接头--2分慢接弯头-',
		ptype:'接头',
		brand:'',
		pname:'2分慢接弯头',
		standard:''
	},
	{
		display:'接头--2分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'2分直通快接',
		standard:''
	},
	{
		display:'接头--1分硬插转2分快接-',
		ptype:'接头',
		brand:'',
		pname:'1分硬插转2分快接',
		standard:''
	},
	{
		display:'接头--2分外牙转3分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'2分外牙转3分直通快接',
		standard:''
	},
	{
		display:'接头--3分进水三通（三通球阀）(铁）-',
		ptype:'接头',
		brand:'',
		pname:'3分进水三通（三通球阀）(铁）',
		standard:''
	},
	{
		display:'接头--3分开关球阀-',
		ptype:'接头',
		brand:'',
		pname:'3分开关球阀',
		standard:''
	},
	{
		display:'接头--3分T型三通-',
		ptype:'接头',
		brand:'',
		pname:'3分T型三通',
		standard:''
	},
	{
		display:'接头--3分侧三通-',
		ptype:'接头',
		brand:'',
		pname:'3分侧三通',
		standard:''
	},
	{
		display:'接头--3分内丝牙转2分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'3分内丝牙转2分直通快接',
		standard:''
	},
	{
		display:'接头--3分外丝转3分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'3分外丝转3分弯头快接',
		standard:''
	},
	{
		display:'接头--3分外牙转2分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'3分外牙转2分弯头快接',
		standard:''
	},
	{
		display:'接头--3分外牙转2分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'3分外牙转2分直通快接',
		standard:''
	},
	{
		display:'接头--3分外牙转3分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'3分外牙转3分直通快接',
		standard:''
	},
	{
		display:'接头--3分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'3分弯头快接',
		standard:''
	},
	{
		display:'接头--3分直通-',
		ptype:'接头',
		brand:'',
		pname:'3分直通',
		standard:''
	},
	{
		display:'接头--3分转2分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'3分转2分直通快接',
		standard:''
	},
	{
		display:'接头--4分外牙转2分外牙直通-',
		ptype:'接头',
		brand:'',
		pname:'4分外牙转2分外牙直通',
		standard:''
	},
	{
		display:'接头--4分内牙转2分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'4分内牙转2分弯头快接',
		standard:''
	},
	{
		display:'接头--4分内牙转2分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'4分内牙转2分直通快接',
		standard:''
	},
	{
		display:'接头--4分内牙转3分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'4分内牙转3分直通快接',
		standard:''
	},
	{
		display:'接头--4分内牙转3分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'4分内牙转3分弯头快接',
		standard:''
	},
	{
		display:'接头--4分对丝-',
		ptype:'接头',
		brand:'',
		pname:'4分对丝',
		standard:''
	},
	{
		display:'接头--4分外牙转2分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'4分外牙转2分弯头快接',
		standard:''
	},
	{
		display:'接头--4分外牙转2分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'4分外牙转2分直通快接',
		standard:''
	},
	{
		display:'接头--4分外牙转3分弯头快接-',
		ptype:'接头',
		brand:'',
		pname:'4分外牙转3分弯头快接',
		standard:''
	},
	{
		display:'接头--4分外牙转3分直通快接-',
		ptype:'接头',
		brand:'',
		pname:'4分外牙转3分直通快接',
		standard:''
	},
	{
		display:'接头--3分隔板接头-',
		ptype:'接头',
		brand:'',
		pname:'3分隔板接头',
		standard:''
	},
	{
		display:'接头--2分隔板接头-',
		ptype:'接头',
		brand:'',
		pname:'2分隔板接头',
		standard:''
	},
	{
		display:'接头--2分龙头快接直通-',
		ptype:'接头',
		brand:'',
		pname:'2分龙头快接直通',
		standard:''
	},
	{
		display:'接头--万能接头(黑色）-',
		ptype:'接头',
		brand:'',
		pname:'万能接头(黑色）',
		standard:''
	},
	{
		display:'接头--万能接头（白色塑料）-',
		ptype:'接头',
		brand:'',
		pname:'万能接头（白色塑料）',
		standard:''
	},
	{
		display:'接头--6分堵头-',
		ptype:'接头',
		brand:'',
		pname:'6分堵头',
		standard:''
	},
	{
		display:'接头--水泵接头（黑色）-',
		ptype:'接头',
		brand:'',
		pname:'水泵接头（黑色）',
		standard:''
	},
];
