var waterPumpList = [
	{
		display:'水泵-三角洲-自吸泵50G-',
		ptype:'水泵',
		brand:'三角洲',
		pname:'自吸泵50G',
		standard:''
	},
	{
		display:'水泵-三角洲-自吸泵200G-',
		ptype:'水泵',
		brand:'三角洲',
		pname:'自吸泵200G',
		standard:''
	},
	{
		display:'水泵-三角洲-增压泵50G-',
		ptype:'水泵',
		brand:'三角洲',
		pname:'增压泵50G',
		standard:''
	},
	{
		display:'水泵-三角洲-增压泵100G-',
		ptype:'水泵',
		brand:'三角洲',
		pname:'增压泵100G',
		standard:''
	},
	{
		display:'水泵-三角洲-增压泵200G-',
		ptype:'水泵',
		brand:'三角洲',
		pname:'增压泵200G',
		standard:''
	},
	{
		display:'水泵-三角洲-增压泵300G(可调试的）-',
		ptype:'水泵',
		brand:'三角洲',
		pname:'增压泵300G(可调试的）',
		standard:''
	},
	{
		display:'水泵-邓元-增压泵50G-',
		ptype:'水泵',
		brand:'邓元',
		pname:'增压泵50G',
		standard:''
	},
	{
		display:'水泵-邓元-增压泵75G(黑色标签）-',
		ptype:'水泵',
		brand:'邓元',
		pname:'增压泵75G(黑色标签）',
		standard:''
	},
	{
		display:'水泵-邓元-增压泵100G（蓝色标签）-',
		ptype:'水泵',
		brand:'邓元',
		pname:'增压泵100G（蓝色标签）',
		standard:''
	},
	{
		display:'水泵-邓元-增压泵200G-',
		ptype:'水泵',
		brand:'邓元',
		pname:'增压泵200G',
		standard:''
	},
	{
		display:'水泵-邓元-增压泵300G-',
		ptype:'水泵',
		brand:'邓元',
		pname:'增压泵300G',
		standard:''
	},
	{
		display:'水泵-邓元-自吸泵50G-',
		ptype:'水泵',
		brand:'邓元',
		pname:'自吸泵50G',
		standard:''
	},
	{
		display:'水泵-柏繁绿泵-柏繁绿泵50G-',
		ptype:'水泵',
		brand:'柏繁绿泵',
		pname:'柏繁绿泵50G',
		standard:''
	},
	{
		display:'水泵-日月谭泵-日月谭泵400G-',
		ptype:'水泵',
		brand:'日月谭泵',
		pname:'日月谭泵400G',
		standard:''
	},
];
